server {
    listen 9009;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # LA MAGIA ESTÁ AQUÍ:
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Para evitar errores 404 en archivos estáticos (imágenes, css)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
        root /usr/share/nginx/html;
    }
}